- name: Update and upgrade apt packages
  apt:
    update_cache: yes
    upgrade: yes
- name: install pip3
  apt: name=python3-pip state=present 
- name: Install Docker SDK for Python
  pip:
    name: "docker<5"
  become: yes
- name: Run mongo container
  docker_container:
    name: 'some-mongo'
    restart_policy: 'always'
    published_ports: '27017:27017'
    volumes:
      - /data/mongo:/data/db
    image: mongo:4.4.1
