# This playbook deploys the CMS app

- hosts: apps

  roles:
    - {
        role: "service",
        service_name: "cms",
        docker_env: {
            HOST: "0.0.0.0",
            PORT: "{{ external_port | string }}", # The port where to serve the app
            CMS_URL: "https://{{ domain }}",
            APP_KEYS: "{{ app_keys }}",
            API_TOKEN_SALT: "{{ token_salt }}",
            ADMIN_JWT_SECRET: "{{ admin_jwt_secret }}",
            TRANSFER_TOKEN_SALT: "{{ transfer_token_salt }}",
            ENCRYPTION_KEY: "{{ encryption_key }}",
            DATABASE_CLIENT: "postgres",
            DATABASE_HOST: "{{ pg_host }}",
            DATABASE_PORT: "{{ pg_port | string }}",
            DATABASE_NAME: "{{ pg_database }}",
            DATABASE_PASSWORD: "{{ pg_password }}",
            DATABASE_USERNAME: "{{ pg_username }}",
            DATABASE_SSL: "false",
            JWT_SECRET: "{{ jwt_secret }}",
        },
        # Some parameters are commented as they are inherited in roles
        # registry: "{{ registry }}",
        # registry_username: "{{ registry_username }}",
        # registry_password: "{{ registry_password }}",
        # docker_image: "{{ docker_image }}",
        volume_host: "/var/www/html/cms",
        volume_container: "/cms/public",
        port_container: "{{ external_port | int }}",
        port_nginx: "{{ internal_port }}",
        # domain: "{{ domain }}",
        # cerbot_email: "{{ certbot_email }}",
      }
