# This playbook deploys the rest app

- hosts: apps

  roles:
    - {
        role: "service",
        service_name: "rest",
        repository: "git@github.com:thefirstspine/rest.git",
        deploy_private_key: "{{ deployment_private_key }}",
        docker_env: {
            PORT: "8080", # The port where to serve the app
        },
        port_container: "8080",
        port_nginx: "{{ service_rest_internal_port }}",
        domain: "{{ service_rest_domain }}",
        cerbot_email: "{{ certbot_email }}",
        when: service_rest|d('') == true
      }
