# This playbook deploys the arena_refuge app

- hosts: apps

  roles:
    - {
        role: "service",
        service_name: "arena_refuge",
        repository: "git@github.com:thefirstspine/arena.git",
        deploy_private_key: "/volume/keys/id",
        docker_env: {
            BOTS_URL: "https://{{ service_bots_domain }}",
            AUTH_URL: "https://{{ service_auth_domain }}",
            MESSAGING_URL: "https://{{ service_messaging_domain }}",
            REST_URL: "https://{{ service_rest_domain }}",
            ROOMS_URL: "https://{{ service_rooms_domain }}",
            SHOP_URL: "https://{{ service_shop_domain }}",
            CALENDAR_URL: "https://{{ service_calendar_domain }}",
            MONGO_HOST: "{{ service_arena_refuge_mongo_host }}", # MongoDB database host
            PRIVATE_KEY: "{{ service_arena_refuge_private_key }}", # Private key to validate protected incoming requests
            BOTS_PUBLIC_KEY: "{{ service_arena_refuge_bots_public_key }}", # Public key to interact with protected service
            MESSAGING_PUBLIC_KEY: "{{ service_arena_refuge_messaging_public_key }}", # Public key to interact with protected service
            ROOMS_PUBLIC_KEY: "{{ service_arena_refuge_rooms_public_key }}", # Public key to interact with protected service
            SHOP_PUBLIC_KEY: "{{ service_arena_refuge_shop_public_key }}", # Public key to interact with protected service
            PORT: "8080", # The port where to serve the app
        },
        port_container: "8080",
        port_nginx: "{{ service_arena_refuge_internal_port }}",
        domain: "{{ service_arena_refuge_domain }}",
        cerbot_email: "{{ certbot_email }}",
        when: service_arena_refuge
      }
