# This playbook deploys the website app

- hosts: apps

  roles:
    - {
        role: "service",
        service_name: "website",
        repository: "git@github.com:thefirstspine-org/website2.git",
        branch: "{{ lookup('ansible.builtin.env', 'BRANCH')|default('master', True) }}",
        git_ssh_key: "{{ git_ssh_key_template }}",
        docker_env: {
            GAME_ASSETS_URL: "https://{{ service_game_assets_domain }}",
            ARENA_URL: "https://{{ service_arena_domain }}",
            AUTH_URL: "https://{{ service_auth_domain }}",
            CMS_URL: "https://{{ service_cms_domain }}",
            CMS_TOKEN: "{{ service_website_cms_token }}",
            SESSION_SECRET: "{{ service_website_session_secret | int }}",
            PORT: "{{ service_website_external_port | int }}", # The port where to serve the app
            LOGS_BETTERSTACK: "true",
            LOGS_BETTERSTACK_SERVICE: "website:{{ env }}",
        },
        port_container: "{{ service_website_external_port | int }}",
        port_nginx: "{{ service_website_internal_port }}",
        domain: "{{ service_website_domain }}",
        cerbot_email: "{{ certbot_email }}",
        when: service_website|d('') == true
      }
