# This playbook deploys the rest app

- hosts: apps

  roles:
    - {
        role: "service",
        service_name: "rest",
        repository: "git@github.com:thefirstspine/rest.git",
        branch: "{{ lookup('ansible.builtin.env', 'BRANCH')|default('master', True) }}",
        deploy_private_key: "{{ deployment_private_key }}",
        docker_env: {
            PORT: "{{ service_rest_external_port }}", # The port where to serve the app
            LOGS_LOGGLY_SUBDOMAIN: "{{ loggly_subdomain }}",
            LOGS_LOGGLY_TOKEN: "{{ loggly_token }}",
        },
        port_container: "{{ service_rest_external_port }}",
        port_nginx: "{{ service_rest_internal_port }}",
        domain: "{{ service_rest_domain }}",
        cerbot_email: "{{ certbot_email }}",
        when: service_rest|d('') == true
      }
