# This playbook deploys the bots app

- hosts: apps

  roles:
    - {
        role: "service",
        service_name: "bots",
        repository: "git@github.com:thefirstspine/bots.git",
        branch: "{{ lookup('ansible.builtin.env', 'BRANCH')|default('master', True) }}",
        deploy_private_key: "{{ deployment_private_key }}",
        docker_env: {
            PORT: "{{ service_bots_external_port | int }}", # The port where to serve the app
            CREDENTIALS: "{{ service_bots_credentials }}",
            PRIVATE_KEY: "{{ service_bots_private_key }}",
            LOGS_DD_API_KEY: "{{ dd_api_key }}",
            LOGS_DD_HOSTNAME: "{% if lookup('ansible.builtin.env', 'BRANCH')|default('master', True) == 'master' %}prod{% else %}dev{% endif %}",
            LOGS_DD_SERVICE: "bots",
        },
        port_container: "{{ service_bots_external_port | int }}",
        port_nginx: "{{ service_bots_internal_port }}",
        domain: "{{ service_bots_domain }}",
        cerbot_email: "{{ certbot_email }}",
        when: service_bots|d('') == true
      }
