# This playbook provision all the servers

# Remember to allow only trusted trafic (e.g. whitelisted IPs, internal network, etc.) in the
# databases servers. The MongoDB database does not provides password by default.

# Provision apps servers
- hosts: apps
  vars:
    certbot_auto_renew: false
  roles:
  - nginx
  - certbot
  - docker

# Provision database servers
- hosts: dbs
  roles:
    - docker
    - role: docker-pgsql
      password: thisissecret!sshhh # Change that placeholder password - and encrypt it with Vault!
    - docker-mongodb
    - role: pgsql-database
      database: auth
      user: auth
      password: thisissecret!sshhh # Change that placeholder password - and encrypt it with Vault!
    - role: pgsql-database
      database: calendar
      user: calendar
      password: thisissecret!sshhh # Change that placeholder password - and encrypt it with Vault!
    - role: pgsql-database
      database: drifters_tales_worlds
      user: drifters_tales_worlds
      password: thisissecret!sshhh # Change that placeholder password - and encrypt it with Vault!
    - role: pgsql-database
      database: rooms
      user: rooms
      password: thisissecret!sshhh # Change that placeholder password - and encrypt it with Vault!
    - role: pgsql-database
      database: shop
      user: shop
      password: thisissecret!sshhh # Change that placeholder password - and encrypt it with Vault!
    - role: pgsql-database
      database: solid_pancake
      user: solid_pancake
      password: thisissecret!sshhh # Change that placeholder password - and encrypt it with Vault!
    - role: pgsql-database
      database: website
      user: website
      password: thisissecret!sshhh # Change that placeholder password - and encrypt it with Vault!
