# This playbook provision all the servers

# Apply common configuration to all hosts
- hosts: apps
  vars:
    certbot_auto_renew: false
  roles:
  - nginx
  - certbot
  - docker

# Configure and deploy database servers.
- hosts: dbs
  roles:
    - docker
    - docker-pgsql
    - docker-mongodb
    - role: pgsql-database
      database: auth
      user: auth
      password: thisissecret!sshhh # Change that placeholder password - and encrypt it with Vault!
