name: deploy matches

on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Clone repo
        uses: actions/checkout@v2
        with:
          repository: thefirstspine/ansible
          path: workspace
      -
        name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: workspace
          push: false
          tags: thefirstspine/ansible:latest
      -
        name: Remove placeholder conf
        run: |
          rm -r workspace/volume/conf
          ls -la
      -
        name: Clone secrets to conf
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.SECRET_REPO_PATH }}
          path: workspace/volume/conf
          token: ${{ secrets.SECRET_REPO_TOKEN }}
      -
        name: Deploy matches
        run: |
          docker run --rm -i -v ./volume:/volume thefirstspine/ansible ansible-playbook -i /volume/conf/inventory.yaml /volume/playbooks/deploy-matches.yaml
